on:
  push:
    branches:
      - 'main'
      - 'dev'

name: test-macos-shell

jobs:
  test-macos-shell:
    runs-on: macos-12
    steps:
      - name: clone-branch
        run: |
          git clone -b dev https://github.com/Defirence/pyenv-buildtools-script.git
          printf "List files and cd into repo dir on runner..."
          ls -lah
          cd pyenv-buildtools-script
          ls -lah
          echo $PWD
      - name: run-macos-shell-tests
        run: |
          printf "Running tests against the script on macos-12.5..."
          ls -lah
          echo $PWD
          brew update
          brew upgrade -f
          cd pyenv-buildtools-script
          chmod +x ./install-python-buildenv-macos.sh
          sh ./install-python-buildenv-macos.sh
          printf "Tests run against the script are complete on the macos-12.5 image..."
